---
- name: Generate device configuration
  hosts: all
  gather_facts: false
  vars:
    output_dir: intended
  tasks:
    - name: Load site variables if defined
      include_vars:
        file: "group_vars/{{ site }}.yml"
      when: site is defined
      ignore_errors: yes

    - name: Ensure output directories
      file:
        path: "{{ output_dir }}/structured_config"
        state: directory
      delegate_to: localhost

    - name: Ensure configs directory
      file:
        path: "{{ output_dir }}/configs"
        state: directory
      delegate_to: localhost

    - name: Write structured configuration
      copy:
        dest: "{{ output_dir }}/structured_config/{{ inventory_hostname }}.json"
        content: "{{ {'hostname': inventory_hostname, 'interfaces': interfaces | default([]), 'clock': clock | default(None), 'bgp': bgp | default(None)} | to_nice_json }}"
      delegate_to: localhost

    - name: Determine vendor template
      set_fact:
        vendor_template: "{{ vendor | default('openconf') | lower | replace('.', '_') }}"

    - name: Render vendor configuration
      template:
        src: "templates/{{ vendor_template }}.j2"
        dest: "{{ output_dir }}/configs/{{ inventory_hostname }}.txt"
      when: vendor_template != 'openconf'
      delegate_to: localhost

    - name: Save OpenConf as vendor config when vendor=openconf
      copy:
        dest: "{{ output_dir }}/configs/{{ inventory_hostname }}.txt"
        content: "{{ {'hostname': inventory_hostname, 'interfaces': interfaces | default([]), 'clock': clock | default(None), 'bgp': bgp | default(None)} | to_nice_json }}"
      when: vendor_template == 'openconf'
      delegate_to: localhost
